import { Subject, Eixo, Book } from './types';

export const ALL_SUBJECTS: Subject[] = Object.values(Subject);

export const SUBJECT_TO_EIXO_MAP: Map<Subject, Eixo> = new Map([
  [Subject.FILOSOFIA, Eixo.HUMANAS],
  [Subject.SOCIOLOGIA, Eixo.HUMANAS],
  [Subject.HISTORIA, Eixo.HUMANAS],
  [Subject.GEOGRAFIA, Eixo.HUMANAS],
  [Subject.PROJETO_VIDA, Eixo.HUMANAS],
  [Subject.BIOLOGIA, Eixo.NATUREZA],
  [Subject.FISICA, Eixo.NATUREZA],
  [Subject.QUIMICA, Eixo.NATUREZA],
  [Subject.ARTE, Eixo.LINGUAGENS],
  [Subject.PORTUGUES, Eixo.LINGUAGENS],
  [Subject.INGLES, Eixo.LINGUAGENS],
  [Subject.EDUCACAO_FISICA, Eixo.LINGUAGENS],
  [Subject.MATEMATICA, Eixo.MATEMATICA],
  [Subject.PROGRAMACAO, Eixo.COMPUTACAO],
  [Subject.PENSAMENTO_COMPUTACIONAL, Eixo.COMPUTACAO],
]);

export const BOOK_DATA: Record<Eixo, { textbooks: Book[]; projects: Book[] }> = {
  [Eixo.HUMANAS]: {
    textbooks: [
      { code: '0092P26041', title: 'Conexão humana', publisher: 'Leya' },
      { code: '0054P26041', title: 'Confluências: ciências humanas e sociais', publisher: 'FTD' },
      { code: '0064P26041', title: 'Diálogos e reflexões', publisher: 'IBEP' },
      { code: '0117P26041', title: 'Diálogos em sociedade', publisher: 'Saraiva Educação' },
      { code: '0029P26041', title: 'Horizontes em diálogo', publisher: 'Editora Positivo' },
      { code: '0038P26041', title: 'Humanidades em foco', publisher: 'Quinteto Editorial' },
      { code: '0022P26041', title: 'Mosaico social: ciências humanas e sociais', publisher: 'Editora do Brasil' },
      { code: '0047P26041', title: 'Percursos e territórios', publisher: 'Edições SM' },
      { code: '0109P26041', title: 'Perspectivas do humano', publisher: 'Moderna' },
      { code: '0127P26041', title: 'Tessituras humanas', publisher: 'Ática' },
    ],
    projects: [
      { code: '0023P260102204000', title: 'MODERNA EM PROJETOS: Ciências Humanas', publisher: 'Editora Moderna Ltda' },
      { code: '0060P260102204000', title: 'HORIZONTES - CIÊNCIAS HUMANAS', publisher: 'Editora FTD S.A.' },
      { code: '0061P260102204000', title: 'CIÊNCIAS HUMANAS EM MOVIMENTO', publisher: 'Editora FTD S.A.' },
      { code: '0079P260102204000', title: 'INTERAÇÃO PROJETOS INTEGRADORES - CIÊNCIAS HUMANAS E SOCIAIS APLICADAS', publisher: 'EDITORA DO BRASIL SA' },
      { code: '0114P260102204000', title: 'DO SEU JEITO', publisher: 'EDITORA ATICA S.A.' },
    ],
  },
  [Eixo.NATUREZA]: {
    textbooks: [
        { code: '0064P26031', title: 'Autoria em ciências da natureza', publisher: 'IBEP' },
        { code: '0047P26031', title: 'Cenários da natureza', publisher: 'Edições SM' },
        { code: '0022P26031', title: 'Coleção mosaico: ciências da natureza', publisher: 'Editora do Brasil' },
        { code: '0109P26031', title: 'Conexões com a natureza', publisher: 'Moderna' },
        { code: '0054P26031', title: 'Natureza e pensamento', publisher: 'FTD' },
        { code: '0038P26031', title: 'Natureza em movimento', publisher: 'Quinteto Editorial' },
        { code: '0127P26031', title: 'Natureza em perspectiva', publisher: 'Ática' },
        { code: '0117P26031', title: 'Olhar e investigar a natureza', publisher: 'Saraiva Educação' },
        { code: '0029P26031', title: 'Plural ciências da natureza', publisher: 'Editora Positivo' },
    ],
    projects: [
      { code: '0022P260102203000', title: 'MODERNA EM PROJETOS: Ciências da Natureza', publisher: 'Editora Moderna Ltda' },
      { code: '0059P260102203000', title: 'CIÊNCIAS DA NATUREZA EM MOVIMENTO', publisher: 'Editora FTD S.A.' },
      { code: '0078P260102203000', title: 'INTERAÇÃO PROJETOS INTEGRADORES - CIÊNCIAS DA NATUREZA E SUAS TECNOLOGIAS', publisher: 'EDITORA DO BRASIL SA' },
      { code: '0156P260102203000', title: 'Ciências da Natureza em projetos integradores', publisher: 'FENIX LIVRARIA E DISTRIBUIDORA DE LIVROS - EIRELI' },
    ],
  },
  [Eixo.LINGUAGENS]: {
    textbooks: [
        { code: '0109P26011', title: '(Re)conectar linguagens', publisher: 'Moderna' },
        { code: '0054P26011', title: 'Acordes: linguagens', publisher: 'FTD' },
        { code: '0022P26011', title: 'Aquarela linguagens', publisher: 'Editora do Brasil' },
        { code: '0064P26011', title: 'Ciranda de linguagens', publisher: 'IBEP' },
        { code: '0092P26011', title: 'Conexão e uso: linguagens', publisher: 'Leya' },
        { code: '0038P26011', title: 'Contato: linguagens', publisher: 'Quinteto Editorial' },
        { code: '0047P26011', title: 'Entrelinhas e travessias', publisher: 'Edições SM' },
        { code: '0117P26011', title: 'Expressão e identidade', publisher: 'Saraiva Educação' },
        { code: '0002P26011', title: 'Ímpar: linguagens', publisher: 'Base Editorial' },
        { code: '0147P26011', title: 'Linguagens em rede', publisher: 'Palavras Projetos Editoriais' },
        { code: '0029P26011', title: 'Plural: linguagens', publisher: 'Editora Positivo' },
        { code: '0127P26011', title: 'Ponto de articulação', publisher: 'Ática' },
        { code: '0023P26011', title: 'Todas as letras: linguagens', publisher: 'Editora do Brasil' },
    ],
    projects: [
      { code: '0054P260102201000', title: 'LINGUAGENS EM MOVIMENTO', publisher: 'Editora FTD S.A.' },
      { code: '0055P260102201000', title: 'HORIZONTES - LINGUAGENS', publisher: 'Editora FTD S.A.' },
      { code: '0089P260102201000', title: 'IDENTIDADE SARAIVA - Projetos Integradores', publisher: 'SARAIVA EDUCACAO S.A.' },
      { code: '0154P260102201000', title: 'Linguagens em projetos integradores', publisher: 'FENIX LIVRARIA E DISTRIBUIDORA DE LIVROS - EIRELI' },
    ],
  },
  [Eixo.MATEMATICA]: {
    textbooks: [
        { code: '0054P26021', title: '#Contemporânea Matemática', publisher: 'FTD' },
        { code: '0109P26021', title: 'Conexão Matemática', publisher: 'Moderna' },
        { code: '0047P26021', title: 'Matemática: compreensão e prática', publisher: 'Edições SM' },
        { code: '0127P26021', title: 'Matemática: contexto e aplicações', publisher: 'Ática' },
        { code: '0064P26021', title: 'Matemática: diálogos e conexões', publisher: 'IBEP' },
        { code: '0117P26021', title: 'Matemática: novos olhares', publisher: 'Saraiva Educação' },
        { code: '0038P26021', title: 'Matemática em foco', publisher: 'Quinteto Editorial' },
        { code: '0029P26021', title: 'Plural Matemática', publisher: 'Editora Positivo' },
        { code: '0022P26021', title: 'Práxis Matemática', publisher: 'Editora do Brasil' },
    ],
    projects: [
      { code: '0021P260102202000', title: 'MODERNA EM PROJETOS: Matemática', publisher: 'Editora Moderna Ltda' },
      { code: '0077P260102202000', title: 'INTERAÇÃO PROJETOS INTEGRADORES - MATEMÁTICA E SUAS TECNOLOGIAS', publisher: 'EDITORA DO BRASIL SA' },
      { code: '0090P260102202000', title: 'IDENTIDADE SARAIVA - Projetos Integradores', publisher: 'SARAIVA EDUCACAO S.A.' },
      { code: '0150P260102202000', title: 'Projetos Integradores: Tempo Jovem', publisher: 'Kits Editora Comércio e Indústria Ltda' },
    ],
  },
  [Eixo.COMPUTACAO]: {
    textbooks: [
        { code: '0109P26081', title: 'Ctrl+alt+play', publisher: 'Moderna' },
        { code: '0054P26081', title: 'Expressão digital', publisher: 'FTD' },
        { code: '0064P26081', title: 'Like: educação digital', publisher: 'IBEP' },
        { code: '0029P26081', title: 'Mundo digital', publisher: 'Editora Positivo' },
        { code: '0047P26081', title: 'Nós na rede', publisher: 'Edições SM' },
        { code: '0127P26081', title: 'Ponto com: educação digital', publisher: 'Ática' },
        { code: '0117P26081', title: 'Redes e conexões: educação digital', publisher: 'Saraiva Educação' },
    ],
    projects: [
      { code: '0012P260101201813', title: 'MODERNA PLUS - Educação Digital', publisher: 'Editora Moderna Ltda' },
      { code: '0036P260101201813', title: 'EDUCAÇÃO DIGITAL POR TODA PARTE', publisher: 'Editora FTD S.A.' },
      { code: '0037P260101201813', title: '360° EDUCAÇÃO DIGITAL', publisher: 'Editora FTD S.A.' },
      { code: '0067P260101201813', title: 'INTERAÇÃO EDUCAÇÃO DIGITAL', publisher: 'EDITORA DO BRASIL SA' },
      { code: '0085P260101201813', title: 'IDENTIDADE SARAIVA', publisher: 'SARAIVA EDUCACAO S.A.' },
      { code: '0098P260101201813', title: 'SER PROTAGONISTA EDUCAÇÃO DIGITAL', publisher: 'EDIÇÕES SM LTDA' },
      { code: '0108P260101201813', title: 'Saberes da Educação Digital', publisher: 'Terra Sul Editora EIRELI' },
      { code: '0116P260101201813', title: 'Educação Digital: Por Dentro da Matrix', publisher: 'Editora Immanuel Kant Ltda' },
      { code: '0135P260101201813', title: 'MUNDO DIGITAL - MODO DE USAR', publisher: 'EDITORA AJS LTDA.' },
      { code: '0163P260101201813', title: 'Consciência: uma jornada pela Educação Digital', publisher: 'PROSA NOVA EDITORA DE LIVROS LTDA' },
    ],
  },
};